Models/Task02/Link/LinkModel.cs
using System;

namespace Task02onCore3.Models.Task02
{
    public class LinkModel
    {
        public Guid? Id { get; set; }
        public string Name { get; set; }
        public Guid UserID { get; set; }
        public string LongLink { get; set; }
        public string ShortLink { get; set; }
        public int RedirectedCount { get; set; }
        public bool Status { get; set; }

        public Guid? GroupId { get; set; }
        public GroupModel Group { get; set; }
    }
}

Controllers/GroupController.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Task02onCore3.Data;
using Task02onCore3.Models.Task02;
using Task02onCore3.Services;

namespace Task02onCore3.Controllers
{
    [Authorize]
    public class GroupController : Controller
    {
        private readonly GroupService groupService;
        private readonly Guid UserID;

        public GroupController(Context db, DbContextOptions<Context> options, IHttpContextAccessor httpContextAccessor)
        {
            groupService = new GroupService(db);
            UserID = Guid.Parse(httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
        }

        // GET: Group
        public async Task<IActionResult> Index()
        {
            //ViewBag.Counts = groupService.LinksCountInGroups(UserID);
            return View(await groupService.LinksCountInGroups(UserID));
        }

        // GET: Group/Details/5
        //public async Task<IActionResult> Details(Guid id)
        //{
        //    GroupModel item;
        //    try
        //    {

        //        item = await groupService.GetById(UserID, id);
        //        if (item == null)
        //        {
        //            return NotFound();
        //        }

        //        return View(item);
        //    }
        //    catch (MethodAccessException)
        //    {
        //        return Forbid();
        //    }
        //}

        // GET: Group/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Group/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string test, GroupModel item)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string tmp = test;

                    item.Id = Guid.NewGuid();
                    item.UserID = UserID;
                    item.Status = true;
                    await groupService.Create(UserID, item);
                    return RedirectToAction(nameof(Index));
                }
                return View(item);
            }
            catch (MethodAccessException)
            {
                return Forbid();
            }
            
        }

        // GET: Group/Edit/5
        //public async Task<IActionResult> Edit(Guid? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var groupModel = await _context.Groups.FindAsync(id);
        //    if (groupModel == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(groupModel);
        //}

        //// POST: Group/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,UserName,Status")] GroupModel groupModel)
        //{
        //    if (id != groupModel.Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(groupModel);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!GroupModelExists(groupModel.Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(groupModel);
        //}

        // GET: Group/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                await groupService.Delete(UserID, id);
                return Redirect(Request.Headers["Referer"].ToString());
            }
            catch (MethodAccessException)
            {
                return Forbid();
            }
        }

        // POST: Group/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(Guid id)
        //{
        //    var groupModel = await _context.Groups.FindAsync(id);
        //    _context.Groups.Remove(groupModel);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        //private bool GroupModelExists(Guid id)
        //{
        //    return _context.Groups.Any(e => e.Id == id);
        //}

        public async Task<IActionResult> ChangeStatus(Guid id)
        {
            try
            {
                await groupService.ChangeStatus(UserID, id);
                return RedirectToAction(nameof(Index));
            }
            catch (MethodAccessException)
            {
                return Forbid();
            }
        }

    }
}

Controllers/LinkController.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Task02onCore3.Data;
using Task02onCore3.Models.Task02;
using Task02onCore3.Services;

namespace Task02onCore3.Controllers
{
    [Authorize]
    public class LinkController : Controller
    {
        private readonly LinkService linkService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly Guid UserID;

        public LinkController(Context db, DbContextOptions<Context> options, IHttpContextAccessor httpContextAccessor)
        {
            linkService = new LinkService(db);
            _httpContextAccessor = httpContextAccessor;
            UserID = Guid.Parse(_httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
        }

        // GET: Link
        public async Task<IActionResult> Index(Guid? groupID)
        {
            try
            {
                ViewBag.groupID = groupID;
                return View(await linkService.GetAll(UserID, groupID));
            }
            catch (MethodAccessException)
            {
                return Forbid();
            }
        }

        // GET: Link/Details/5
        //public async Task<IActionResult> Details(Guid id)
        //{
        //    LinkModel linkModel;
        //    try
        //    {
        //        linkModel = await linkService.GetById(UserID, id);
        //        if (linkModel == null)
        //        {
        //            return NotFound();
        //        }

        //        return View(linkModel);
        //    }
        //    catch(MethodAccessException)
        //    {
        //        return Forbid();
        //    }
        //}

        // GET: Link/Create
        public IActionResult Create(Guid groupId)
        {
            try
            {
                if (!linkService.IsGroupExistence(UserID,groupId))
                    throw new MethodAccessException();
                ViewBag.GroupId = groupId;
                return View();
            }
            catch (MethodAccessException)
            {
                return Forbid();
            }
        }

        // POST: Link/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LinkModel item)
        {
            try
            {
                if (!linkService.IsGroupExistence(UserID, item.GroupId))
                    throw new MethodAccessException();
                item.UserID = UserID;
                item.Id = Guid.NewGuid();
                item.Status = true;
                if (ModelState.IsValid)
                {
                    string absoluteServerUrl = string.Format("{0}://{1}", Request.Scheme, Request.Host);
                    await linkService.Create(UserID, item, absoluteServerUrl);
                    return RedirectToAction("Index", "Link", new { item.GroupId});
                }
                return View(item);
            }
            catch (MethodAccessException)            
            {
                return Forbid();
            }
        }

        // GET: Link/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                await linkService.Delete(UserID, id);
                return Redirect(Request.Headers["Referer"].ToString());
            }
            catch (MethodAccessException)
            {
                return Forbid();
            }
        }

        public async Task<ActionResult> ChangeStatus(Guid linkId)
        {
            try
            {
                await linkService.ChangeStatus(UserID, linkId);
                //return RedirectToAction("Index", "Group");
                //return RedirectToAction(nameof(Index));

                return Redirect(Request.Headers["Referer"].ToString());
            }
            catch(MethodAccessException)
            {
                return Forbid();   
            }

        }
    }
}

Views/Link/Create.cshtml
@model Task02onCore3.Models.Task02.LinkModel

@{
    ViewData["Title"] = "Create";
}

    <h1>Adding a new link</h1>

<hr />
<div>
    <img src="~/img/back.png" class="img-btn img-btn-back" onclick="history.back()" />
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Name</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LongLink" class="control-label">Long link</label>
                <input asp-for="LongLink" class="form-control" />
                <span asp-validation-for="LongLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-route-GroupId="@ViewBag.GroupId" type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Link/Index.cshtml
@model IEnumerable<Task02onCore3.Models.Task02.LinkModel>

@{
    ViewData["Title"] = "Index";
}

<h1>My links</h1>
<div>
    @{
        if (ViewBag.GroupId != null)  //links of the group
        {
            <a asp-controller="Group" asp-action="Index" asp-route-GroupId="@ViewBag.GroupId">
                <img src="~/img/back.png" class="img-btn img-btn-back" />
            </a>
        }
    }
</div>
@{
    if (ViewBag.GroupId != null)  //all links
    {
        <p class="add-btn">
            <a asp-action="Create" asp-route-GroupId="@ViewBag.GroupId">
                <img src="~/img/add.png" class="img-btn" /> Создать
            </a>
        </p>
    }
}
@*<p>
        <a asp-action="Create" asp-route-GroupId="@ViewBag.GroupId">Create New</a>
    </p>*@
<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Long link
            </th>
            <th>
                Short link
            </th>
            <th>
                Redirected
            </th>
            <th>
                Status
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr data-linkid="@item.Id">
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <a target="_blank" href="@Html.DisplayFor(modelItem => item.LongLink)">@Html.DisplayFor(modelItem => item.LongLink)</a>
                </td>
                <td>
                    <a target="_blank" href="@Html.DisplayFor(modelItem => item.ShortLink)">@Html.DisplayFor(modelItem => item.ShortLink)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RedirectedCount)
                </td>
                <td>
                        @{ if (item.Status)
                            {
                                <div data-linkid="@item.Id" class="changestatus toggleButton toggleButtonOn">
                                    ON
                                </div>
                            }
                            else
                            {
                                <div data-linkid="@item.Id" class="changestatus toggleButton toggleButtonOff">
                                    OFF
                                </div>
                            }
                        }
                </td>
                <td>
                    <button type="button" data-id="@item.Id" class="btn btn-danger btn-close deleteItem">
                        X
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

<div id="msg-box" aria-live="polite" aria-atomic="true" style="position: absolute; bottom: 100px; right:100px; min-height: 500px;">
    <div style="position: absolute; bottom: 0; right:0;">
        <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-delay="5000" style="width: 400px">
            <div class="toast-header" style="background-color: #dff0d8">
                <strong class="mr-auto">Link deleted</strong>
                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="toast-body msg">
            </div>
        </div>
    </div>
</div>

<script>
    function DeleteLink(linkID) {
            $.ajax({
                url: "api/link/"+linkID,
                contentType: "application/json",
                method: "DELETE",
                success: function (link) {
                    $('tr[data-linkid="' + link.id + '"]').remove();
                    $(".msg").text("You have deleted the link " + link.name + ".");
                    $('.toast').toast("show");
                }
            })
    }

    function ChangeStatus(linkID) {
        $.ajax({
            url: "api/link/" + linkID,
            contentType: "application/json",
            method: "PUT",
            success: function (link) {
                var setter = ($('.changestatus[data-linkid="' + link.id + '"]'));
                if (setter.hasClass("toggleButtonOn")) {
                    setter.text("OFF");
                    $(".msg").text("You have disabled the link " + link.name + ".");
                }
                if (setter.hasClass("toggleButtonOff")) {
                    setter.text("ON");
                    $(".msg").text("You have activated the link " + link.name + ".");
                }
                setter.toggleClass("toggleButtonOn");
                setter.toggleClass("toggleButtonOff");
                $('.toast').toast("show");
            }
        })
    }

    // on delete button click trigger
    $("body").on("click", ".deleteItem", function () {
        var linkID = $(this).data("id");
        //alert("ID элемента: " + groupID);
        DeleteLink(linkID);
    })

    //on changestatus button click trigger
    $("body").on("click", ".changestatus", function () {
        var linkID = $(this).data("linkid");
        var btn = $(this);
        btn.text("...");
        ChangeStatus(linkID);
    })
</script>